notice:					     #å…¬å‘Š
  enable: true
  content: Welcome to my brand new blog!

mode: time    #UI 07:00-19:00

avatar:					     #å¤´åƒ
  url: /image/avatar.jpg 
  rounded: true
  opacity: 1
  status:
    enable: true
    # emoji: ğŸ˜­
    message: ä¸å¿˜åˆå¿ƒ

favicon: /image/seedling-line.svg			#ç½‘ç«™å›¾æ ‡

social:
  - name: E-Mail
    link: mailto:tonylsx611@gmail.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: QQ
    link: /image/qq.jpg
    icon: icon-qq-line
    color: "#12B7F5"
  - name: Wechat
    link: /image/wechat.jpg
    icon: icon-wechat-2-line
    color: "#1AAD19"

banner:
  enable: true
  title: å¿†æ½‡æ¹˜çš„å°ç«™


wordcloud:
  enable: true


menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories         #still constructing...
      path: /categories/
      icon: icon-folder-2-line
    - type: tags                  #still constructing...
      path: /tags/
      icon: icon-price-tag-3-line
  custom:
    title: é˜¿é‡Œäº‘ç›˜
    path: https://www.aliyundrive.com/drive
    icon: icon-cloud-line


pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: https://www.must.icu
    icon: icon-genderless-line
    color: dodgerblue
  - name: Moodle
    url: https://moodle.must.edu.mo
    icon: icon-women-line
    color: hotpink


reward: 						#æ‰“èµ
  enable: true
  icon: icon-hand-coin-line
  comment: I'm so cute. Please give me money.
  methods:
    - name: æ”¯ä»˜å®
      path: /image/alipay.png
      color: "#00A3EE"
      icon: icon-alipay-line

    - name: å¾®ä¿¡æ”¯ä»˜
      path: /image/wechat.png
      color: "#2DC100"
      icon: icon-wechat-pay-line

footer:
  since: 2022
  powered:
    enable: false
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-02-20T00:00:00"

wordcount:
  enable: true
  count: true
  time: true

local_search:
  enable: true

comment:
  enable: true

mourn:   #é»˜å“€æ—¥
  enable: true
  days:
    - "4-4"     #æŠ—å‡»æ–°å† è‚ºç‚
    - "9-18"   #å‹¿å¿˜å›½è€»
    - "12-13" #å—äº¬å¤§å± æ€

katex:
  copy_tex: true
  global: false